### ISSUE TITLE
Still need to install additional package for Fcitx?

### ISSUE THREAD

**Issue by dogs-1985** [fcitx/flatpak-fcitx5#4]
Hi, 

I'm not professional Linux user, just a normal user that want to setup input method in KDE.
I have read this article.

[https://www.csslayer.info/wordpress/fcitx-dev/fcitx5-on-flatpak/](url)
`在本地非 flatpak 程序上使用的话，还需要安装 Fcitx 4/5 的 im module。`

[https://ouyen.github.io/fcitx5-ubuntu/](url)
`安装ficitx5后端`
`sudo apt install fcitx5-frontend-gtk2 fcitx5-frontend-gtk3 fcitx5-frontend-qt5`

#https://github.com/fcitx/fcitx5/issues/108#issuecomment-683123132

Is the Fcitx5 flatpak version still need to install additional backend/frontend package only can function?

**Comment by wengxt** [comment]
To allow your application to use any input method, it need some way to communicate with input method.
While there's an X11 based protocol, XIM, the implementation itself is considered pretty bad and that's why people are all go with the im module (a plugin to gtk/qt that is loaded by application at runtime).

If you really don't want to, the option for you would be
set GTK_IM_MODULE=xim and QT_IM_MODULE=ibus (qt5 removed xim support, but has built-in ibus support).

But still I suggest you use fcitx5's im module, because that's what under our control.

If you install another flatpak app from flatpak runtime, usually the runtime already bundles the fcitx im module (we integrated it into freedesktop runtime, gnome runtime, and kde runtime). But for gtk/qt application on your host, the plugin can only comes from your host package.
